[METADATA]
modified = 2026-08-22T17:03:06.103Z

[[PRINCIPALS]]
name = "BA CREDIT CARD FUNDING"
email = "thayervarine@gmail.com"
website = "https://xrptoolbox.org"
x = "varinethayer"
github = "vthayer"
